use BIAssignment2;

INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('CONVERTIBLE')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('TRACTOR')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('TRACTOR')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('BUS (OMNIBUS)')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('TRACTOR')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('BUS (OMNIBUS)')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('CONVERTIBLE')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('UTILITY')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('REFRIGERATOR TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('TRACTOR')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('DUMP')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('CONVERTIBLE')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('PICKUP TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('VAN TRUCK')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('4 DOOR SEDAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('SUBURBAN')
INSERT INTO vehicle_body_type_1_dim (vehicle_body_type) VALUES ('2 DOOR SEDAN')