use BIAssignment2;

INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Action Prior to Accident')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting from Parking')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Overtaking/Passing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Overtaking/Passing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Other')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Entering Parked Position')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Entering Parked Position')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Not Applicable')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Other')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Unknown')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting from Parking')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making U Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting from Parking')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making U Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Backing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Overtaking/Passing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Avoiding Object in Roadway')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Other')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Overtaking/Passing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Merging')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Right Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Changing Lanes')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Overtaking/Passing')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting from Parking')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Parked')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Stopped in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Starting in Traffic')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Slowing or Stopping')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Making Left Turn')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')
INSERT INTO action_prior_accident_3_dim(action_prior_accident) VALUES ('Going Straight Ahead')