package adventofcode

import "testing"

var input21 = []string{
	"jqtt: tnwg * mbnq",
	"vsww: jmrn + twmm",
	"ppws: qtfb * rdsp",
	"ljqm: 14",
	"bsvb: tbqb - fqqm",
	"wfpq: hgdp * ddvm",
	"jhtm: 2",
	"slnm: rrtr * lhwh",
	"lgzs: jtrw * dfmw",
	"rmwf: pmsv - llsm",
	"przw: bqwv + ghcz",
	"rqwg: 6",
	"psrl: 4",
	"jddv: plnt * gcfc",
	"vtbv: rwmn + zcwm",
	"hgtf: qrlv + brzm",
	"hhlf: 2",
	"qnwv: vhwb + thlf",
	"sbwr: ppws * rlvq",
	"cpld: gwmj + rhcd",
	"nnmv: gjsm * jrpf",
	"ltft: rfvj * cttp",
	"sjzd: 2",
	"fnnl: rpmq * zgms",
	"thmv: 3",
	"slsp: 5",
	"qnhh: crqv + hdgl",
	"lzmd: 2",
	"cfjz: 18",
	"nftb: 3",
	"wndb: ztgl * cwnt",
	"bjbh: hhnq + wchj",
	"hcsl: sbtp + wrnf",
	"wljw: wrmd / ffct",
	"fctr: 2",
	"wnmz: 17",
	"mhfl: 3",
	"crfw: sdvt * gvrz",
	"vqdv: 3",
	"zswr: 4",
	"tbgc: hqzm * qtsc",
	"bcmz: jqbf + vchc",
	"fltj: jlgw / prsv",
	"pnbd: 2",
	"vqcc: 3",
	"pdhb: 11",
	"mssc: hjbb * zzsf",
	"fbcp: pfhh + fhbm",
	"qjlj: 2",
	"bwmp: gwqd + zttp",
	"qqnm: fftd * mbst",
	"rmwh: tcnh - pcmh",
	"ssrc: 2",
	"tlhm: tjfv + zpsf",
	"rnbd: jjvt + hmzp",
	"gbwn: cvlv + djwh",
	"pfpd: 4",
	"nfvs: cpmc + vzhf",
	"ssts: 3",
	"hvbh: 3",
	"fnwt: shzp * thgj",
	"bwjj: wfnf * dtqb",
	"dvll: 1",
	"rjtf: 3",
	"gtrh: lcqd + prrn",
	"pbqm: 1",
	"nlrm: 5",
	"dftz: mzng * tncp",
	"rlsl: ppmh / pvnb",
	"hhgf: dwnr * qbrj",
	"lddg: tbzq * ncwd",
	"pclv: qqnt - gcqz",
	"blhb: rnzq + mhqz",
	"drnr: zlhg + mvcq",
	"hgwl: jqtl + wzsr",
	"zswf: blqr * lvsb",
	"fdbt: pwfs * gnhq",
	"fwlm: 1",
	"wpzv: 3",
	"cdwp: gfhs + wtbp",
	"hzch: fdbd + nrth",
	"pdsl: 3",
	"phql: hbmw * wrlt",
	"ztvt: 1",
	"fgfp: 13",
	"wfjt: 3",
	"wrmd: fhrp * jrdr",
	"cldc: fmgr + cdjg",
	"vfvb: zlgm - stzg",
	"qfrh: hbhc * gnhc",
	"jrdr: 2",
	"fcdv: 3",
	"hjjp: cvmd * qnjb",
	"ftmr: qtbj + gnfr",
	"gqfw: 3",
	"zgzh: phsj + jzrn",
	"cqvn: 7",
	"bbhr: jdbt * ccrh",
	"vrvs: 5",
	"rlvz: pwvl * lczp",
	"smhn: 2",
	"rzhg: 6",
	"qbmc: 3",
	"wtvv: 4",
	"nqnb: 4",
	"zshh: ngfn + ljqm",
	"rpph: hbwt * fwfh",
	"lqqw: grqf * jwfc",
	"jwgt: lwjj * fsfh",
	"wqmw: 4",
	"nzjs: 2",
	"gcvc: 2",
	"pwvl: 16",
	"gwqd: 10",
	"prrn: 4",
	"btrp: 5",
	"mpjh: 2",
	"fbcl: 2",
	"mwbr: 2",
	"lcgw: zpmm + lwfw",
	"dlsw: 1",
	"vwtr: rgsj / vfcg",
	"vhjq: wrvz * dmzh",
	"mdvc: 5",
	"sldj: 5",
	"fwpv: 11",
	"pvqb: qwdt + srzd",
	"ptqg: 12",
	"chzc: 2",
	"vfsz: 3",
	"hjlt: mrgj * ffdp",
	"mvtd: 5",
	"jldc: dvvw * zbwz",
	"bsft: 2",
	"svsd: 9",
	"qcbl: fztd * cpld",
	"hjzq: 3",
	"ctmh: 2",
	"cnss: 2",
	"zqrj: mhhq * fjfc",
	"jsgj: 5",
	"qrmb: 7",
	"nszq: rdhf * zstr",
	"mgsm: 5",
	"zmhz: cglq * cttz",
	"msjt: 3",
	"czrh: cvbr / djtb",
	"lslt: grfq / hsgj",
	"nfcm: 3",
	"ncsj: 14",
	"vgjt: 3",
	"ldzh: 4",
	"lzdj: 8",
	"glrq: 5",
	"cjjr: 11",
	"dnwc: 8",
	"pldf: vcdj * chzc",
	"rfwr: rqcp * qpwg",
	"zblf: 2",
	"swbp: wggc + qcnf",
	"hcjq: jfft * hhll",
	"fjlz: vjdq + dzsp",
	"zswq: wbmt + scrh",
	"tzrc: fflf + mpbq",
	"zsjl: jmdd * mpwj",
	"tmwj: 4",
	"jfvd: 3",
	"jqzf: 2",
	"htzv: tlps + sjjp",
	"gmwm: 7",
	"qbrj: 2",
	"cmdr: lswp * lljh",
	"rtpp: 1",
	"qrdg: slst + bbrq",
	"hqzm: 2",
	"vdsw: 3",
	"hzhv: 6",
	"humn: 927",
	"dzsp: 5",
	"lpsb: 5",
	"jqcq: 5",
	"mvcq: 12",
	"cfhv: 2",
	"qrrf: vqvn - wprq",
	"mznq: sfjb * hvtd",
	"bzfw: 4",
	"nctp: 4",
	"bzjg: hcnm + jtbm",
	"gppp: fnfn * qqnm",
	"ghzf: szlh * bgcc",
	"rfls: gjnf / hffp",
	"nfjz: 4",
	"pqzg: 4",
	"frhd: twtc * rrmn",
	"mvds: 1",
	"hqlh: pwvn * qtvf",
	"wfgr: twsv * tntz",
	"mfsl: dlsw + hlmh",
	"lzlf: szvt + qwcz",
	"cgwz: 14",
	"wvjb: 4",
	"hsnr: 4",
	"dhdl: hmcr * lscn",
	"qmwp: cbdg * mplg",
	"jfft: qjfq + vzpv",
	"tttw: 6",
	"qcsp: 12",
	"cmtc: qtrv * fcfl",
	"zttp: jnbr * sldj",
	"cnrm: 3",
	"mqtj: nhhv * bsdz",
	"twmm: mhbm * ltwj",
	"vphb: fcdv * wgpg",
	"rcpt: 2",
	"sglw: wplj + ffmd",
	"gwqw: pntz - dwzg",
	"bwdq: 3",
	"gjdr: mpqg + qsvs",
	"mgtw: ddgp + cqlr",
	"cgzf: 4",
	"vmpw: btrp + wlhb",
	"cvbn: 4",
	"jcsn: lntg * tmqv",
	"pgdh: frmz + sqth",
	"fqbc: lgzs + zttz",
	"llpw: 8",
	"hbnz: 12",
	"zdll: 19",
	"pbnr: 5",
	"pzcv: 1",
	"wlwl: 2",
	"ljcq: 6",
	"vwgp: 8",
	"thlf: 2",
	"mzqq: pgdh + rmch",
	"dhrn: 5",
	"jbrv: mttw * rjhz",
	"pbgz: 2",
	"tmnw: dfdq - ljmt",
	"ssqj: 6",
	"splf: nlzg / jvrb",
	"pflc: 2",
	"ssmt: rlwg + rppv",
	"gpwh: 3",
	"nncw: 11",
	"ggzr: sqvs * ctcq",
	"vjcm: 2",
	"zdlm: nsrp - nptq",
	"pwfb: 3",
	"glpb: 5",
	"ccrm: ztzh * mjjv",
	"tpnw: smdm + zblf",
	"mnmm: 2",
	"prnd: mwvp / lddf",
	"chfq: sbzg * qqcw",
	"gtcw: drhz + hmqm",
	"lpwm: 4",
	"lnpt: lpcg - gvrg",
	"bmsr: cqrt + mqst",
	"hbsb: lztz * tmll",
	"vcrf: 4",
	"sjwd: 3",
	"mjdq: fcvf * ghzf",
	"dpng: qjvl * htzv",
	"lvsb: 4",
	"msmz: zbvr * ndpr",
	"gzgd: jtvv + djmv",
	"ftsd: 2",
	"tjfh: 2",
	"jggn: cqsq * szrw",
	"vjzc: 5",
	"cvqj: fwlm + qpdm",
	"ngzd: jdvr + hzld",
	"gdzl: 3",
	"svvl: hcsl + tqvn",
	"ldqv: ncqc * pvcl",
	"fgqr: nwsb - glnr",
	"rzmw: 4",
	"rzlb: 5",
	"mvtf: 7",
	"tsbg: tshn * lspr",
	"glmh: 4",
	"mwjj: lfgq + wqqz",
	"rmnq: vmpw + vwtr",
	"lfsd: 3",
	"wdnd: 2",
	"jfps: 2",
	"wzmg: jznb + ntth",
	"lmnv: wmwb * hlgs",
	"zghz: scnm + jgpj",
	"wgjp: slnt + wccg",
	"cmnb: 2",
	"gjnf: jzzv * cfrs",
	"lfwr: cwht + bmsr",
	"qqcw: 2",
	"hmzn: gwjs * tqfv",
	"vvjt: ftmz + bzmt",
	"vdvv: 2",
	"wnmv: 4",
	"vgnz: 3",
	"fmgr: 4",
	"sqvc: dzzd + jrhp",
	"jsgr: znft * lhcl",
	"lfcf: 5",
	"dhhr: rmwf + ffjt",
	"rcbh: tvdm + wccm",
	"lntg: cqpv / gghf",
	"vqqr: dgct + vnjw",
	"tjsp: 2",
	"pnjw: 18",
	"pvfm: 2",
	"tzsj: 2",
	"rcnm: 2",
	"ztqv: 2",
	"vmvw: ccrm + mznq",
	"cqrt: jmgl + ppwv",
	"zlgm: 19",
	"wvjq: pdmg / gnsw",
	"bqzr: 3",
	"qrgd: 2",
	"vggm: fcsl + fttd",
	"lgqq: rqfs * fbcp",
	"djwh: rbqv * mqhn",
	"fmmf: 2",
	"djzw: 2",
	"smcp: vcst * sjwd",
	"mgrb: wdlz + vqsl",
	"rrtm: 2",
	"sfjb: ztvd + gwqj",
	"npfj: fnwt + pznr",
	"dspt: vsts * tnqw",
	"stvq: wdbm * hfmt",
	"dzcg: 13",
	"wzdd: 2",
	"qpvj: 3",
	"fzdf: mfvt * pddw",
	"ctlr: pdvd * jslc",
	"nswl: hnmm + dlzh",
	"stzg: 2",
	"gqbj: 11",
	"fnqs: 7",
	"tdhh: tnsh * tvst",
	"rzcl: 2",
	"bpmb: 5",
	"mrhn: rwpg + jrpz",
	"nvlr: nnmv + sqlb",
	"ddbt: 7",
	"jjtj: 5",
	"pltp: 3",
	"wnbz: 2",
	"nvvg: hswq * wcws",
	"dbqz: 17",
	"qrvb: wvcb - pqnr",
	"jhld: rnbp * glmc",
	"zgfr: sqfh + vsrr",
	"stsp: hsqw + bvrw",
	"mpjq: tsbd / dhrn",
	"rthb: 8",
	"dlnw: 2",
	"jqdd: 1",
	"gjtj: cjmp * zwqp",
	"nqsh: 3",
	"qvcv: fzwz + pqrr",
	"flzc: vfjs / wtst",
	"hbdw: 14",
	"lddb: ctjf * qfdj",
	"bzfn: hvcj * fthj",
	"zzhc: 2",
	"wqbz: 2",
	"plvm: lhtz + vhjq",
	"jhpv: rbjd * tcbd",
	"zngb: qbmc * qcvn",
	"tqzc: 10",
	"zqsh: 4",
	"dfmb: pfnb + tdbd",
	"fgzg: mmpf * dcpn",
	"mqhn: 4",
	"mrzb: zzhp + lzlf",
	"bpmf: mwnp + pvlf",
	"gtgs: 5",
	"gjww: dnwc - rnhf",
	"nqnm: pnff * qhpj",
	"wgjm: 5",
	"vwhs: pjgv + rbnz",
	"nslh: 2",
	"whsc: wnbz * gtrh",
	"fvhq: wnhj * mjtz",
	"wsvb: 2",
	"qjvl: 7",
	"bzdf: hsft - rzsr",
	"rpnt: 12",
	"hmht: 7",
	"jvtp: wmgg * swzv",
	"wjqs: rjjc + hqjp",
	"rbqv: vfsn + gpnm",
	"wbvc: 2",
	"nsrp: zgsv * bpqc",
	"mtcj: vphb - zhmp",
	"pfhh: whhv + zwmn",
	"wlgb: nhtj * bzjg",
	"slsq: 3",
	"mhqd: fjqs + tbpn",
	"hrnl: 2",
	"gjsm: qfnd * gqjd",
	"wzzg: 4",
	"qqqc: stvr * fhtj",
	"ldfg: 2",
	"tbvw: fgfd * llcd",
	"dgnc: 2",
	"vfsn: hgbn * rchb",
	"rcvw: rqqn * hffn",
	"bqwv: tmrt * sggr",
	"trdc: 2",
	"rjhz: 3",
	"jfvf: 3",
	"mzvf: zjjc * vwhv",
	"npgq: 4",
	"qsvs: nnzr - pwnn",
	"rdhz: zwsb * hvdq",
	"rbnz: fdsq * nslh",
	"sdwz: 2",
	"blqr: 3",
	"hffp: 2",
	"dhgm: 14",
	"ffpb: rrzj * qghl",
	"fttd: lcnc * shtd",
	"wgsh: gqlr + zrbh",
	"flbd: wqjh - ltlg",
	"pzzv: bbbd * mgrb",
	"hcvv: 3",
	"sjpr: llcz * zjqd",
	"dmzh: hjvv + ztvt",
	"cfpg: hvvs + frhd",
	"qqrj: fsjs * zdlb",
	"vhvg: lfpm + bfcn",
	"qmgv: 4",
	"dtvz: 4",
	"bmhq: mvjq + rsdq",
	"pwzt: rdtl * jfcq",
	"lnns: 2",
	"gnfr: 16",
	"pwzf: ggmd * njmb",
	"lqlg: cvmv + svgw",
	"hfvc: sdcd * wlwl",
	"rlcr: cqzg / jmnm",
	"rjzg: 13",
	"sngt: 4",
	"vzpv: 13",
	"nfbq: 2",
	"vhbl: mstp + wstd",
	"wglp: 4",
	"gssp: 2",
	"rmln: 2",
	"vfrs: ncsj + lnzz",
	"jgjw: jrpr / jhtm",
	"bbfz: hcvv * nqwl",
	"wqvc: 4",
	"fdwc: 15",
	"ppls: 5",
	"djwr: qrrf * nrcv",
	"jrrb: 3",
	"tbfc: ndbm * bqcb",
	"qjgd: lsjt / nhbd",
	"lpbj: 2",
	"vtts: 9",
	"ldgc: 2",
	"sbsz: njgs * vrdm",
	"svgw: tmrb * pttq",
	"vnfd: 7",
	"hlll: bjln + tpwj",
	"smwm: 10",
	"hhfb: 3",
	"swzv: 3",
	"cfrs: 7",
	"mnvc: 10",
	"vlql: 13",
	"pztl: 13",
	"lmdm: jsrw * zcqd",
	"lqvq: tqcv + djjq",
	"pbvw: 2",
	"mqwb: 4",
	"lspr: zbdp - jjnw",
	"fbvp: 9",
	"gmwv: 4",
	"gzbz: pqzg + sjvs",
	"mtzn: fdfv * hzdl",
	"dsgr: qfrp + slsp",
	"nwwj: 11",
	"dcrj: hdrz * rtmc",
	"pwsz: 4",
	"bgjq: 3",
	"shzp: lzgz * jfvd",
	"mbqd: 19",
	"lnbd: cgzf + cfjz",
	"tmll: 11",
	"pwbd: 7",
	"fjqj: 2",
	"vgvt: 11",
	"trfc: 17",
	"pctn: rprc + lddg",
	"ppwv: 1",
	"fcwq: tbvw * zthj",
	"ssvh: lslt * dmsl",
	"rrzj: smwm + pzlc",
	"jspc: 16",
	"dnws: 5",
	"psch: cvlc / mpzb",
	"pdfv: rmpp + lmnv",
	"hfmt: 3",
	"zhwq: pzrm * zqsh",
	"zfwq: 8",
	"ngmj: swns + gdnd",
	"zrgp: 3",
	"lsqf: 4",
	"rddc: hcjq + vdhj",
	"vmlj: 2",
	"srhh: qnhf + dzpg",
	"grls: ppnt - lchh",
	"hsgc: 2",
	"thnr: trdc * svdc",
	"hgql: pnqr * lhdg",
	"pwct: jmsf + rdjr",
	"vfhc: cvcr + mmtb",
	"frmz: tvcf + vhmm",
	"hlmh: zqzl * stvq",
	"rwpt: 10",
	"fgzh: 13",
	"wcmt: mfdg - prrv",
	"mvqq: 2",
	"dpqh: ghfg / fmmf",
	"ddpt: fnhg + tfqz",
	"pzjg: vdzb + vlzb",
	"pqgw: qlpt - bggz",
	"nnfh: 3",
	"dvbm: 4",
	"jzwg: bpfz * nwwj",
	"mnrl: 8",
	"hzrb: gbmg * rsdz",
	"fdfv: 19",
	"pchj: mtff * cvsr",
	"vspl: 3",
	"lptj: mhtq + qtjs",
	"hzll: 5",
	"dqzh: bhsw + vcwg",
	"hvvs: zbvz + jsgr",
	"bpzr: 4",
	"vwpt: gtss * prhf",
	"snzm: crgq + mqbw",
	"pjch: dlnf * jbjm",
	"gqqr: cffl * dvzq",
	"dpvh: 7",
	"cvbr: mzvf + bdqq",
	"lhcl: 3",
	"gvrz: 2",
	"rfll: hphr / htzp",
	"wgrf: 4",
	"cprz: 1",
	"vdjv: strh * tbfs",
	"wrnf: cmdr + ljvj",
	"svdm: 2",
	"nczr: bzdf * lbgp",
	"nnbq: clvh + fzrq",
	"tgzb: 2",
	"scrh: 11",
	"zzhz: 3",
	"pgzj: 5",
	"tncp: 3",
	"grqf: 5",
	"gjfj: 3",
	"vnvn: mdvc + fsnf",
	"jnmq: 5",
	"tbfs: 3",
	"wntr: whzt * svcj",
	"shnm: ljff * nvbl",
	"jrpz: wsfn * jcjg",
	"zjnz: 6",
	"dtqb: gtcw - wshg",
	"qjlf: wzdd * wgrf",
	"vlww: gplf * hhgf",
	"shtd: szlg + wmqq",
	"sqzh: 2",
	"bbbf: 19",
	"dgzb: 2",
	"pnlb: pmgm * dzcw",
	"hmgj: qppm * nrls",
	"vqpv: gnvb * snzm",
	"lbgp: dlln / tgmj",
	"gjmn: 10",
	"lchl: lgth * vcql",
	"bncq: vjvn * hhlf",
	"vdjf: jldc * zrtl",
	"mdsd: wzpw + gzgp",
	"gcqb: 5",
	"whvw: pbgz * cbgs",
	"lqmt: scvh * vbbc",
	"glwp: 3",
	"tgzh: twrf + bsft",
	"tgmj: 2",
	"gmhc: 11",
	"szvt: 11",
	"hpjw: 5",
	"vbgd: 2",
	"jfpd: 3",
	"mjng: 4",
	"gbmg: ngzd * zvjn",
	"lsdf: sfdm * ntmm",
	"bvwj: rpph / hlhr",
	"gvrg: bsdm + rzhp",
	"zwqg: gwjr + zhhf",
	"sjmt: 14",
	"jpbw: wghm + wqfw",
	"cvsr: mjjc * gmwv",
	"jmnm: 2",
	"mfdh: 2",
	"qfdg: 5",
	"bhzq: 20",
	"vhmm: cvbn + hrbg",
	"cqth: 5",
	"dsnn: dfch * nqnm",
	"bjvl: pdwc * whcg",
	"wfcs: gsfp + hdqs",
	"sljj: vrzh * shjf",
	"zpjz: 2",
	"rnhv: 2",
	"dvvw: 2",
	"pnmd: hgmq + gmqb",
	"wjwb: 17",
	"tpmw: mjdq + pbtf",
	"mpsj: 2",
	"dwlp: tjnn * fngj",
	"hgdp: fshg / cwsw",
	"ptmn: 5",
	"rwww: 4",
	"zgcr: 10",
	"tntz: rcbh + vlsl",
	"pjmq: 2",
	"mmzg: ccbd + qcgq",
	"lnzz: lcdr * wcng",
	"lhbf: qwgh + jzqf",
	"mnbb: wfpq * vfrs",
	"ptdr: dssj * rrfz",
	"qbdg: nrrt * mpmh",
	"strh: lbqd * gdqc",
	"jfqr: bmdd * stsl",
	"mtvl: 2",
	"pvlf: 10",
	"fcbn: sccz + tqgf",
	"fqdl: hmlt / vnph",
	"fnmw: fbcg + hqlv",
	"zphb: gmdb * cmtf",
	"gtfs: 2",
	"cwhm: 9",
	"jgnn: npgp + lhnm",
	"tvst: nfcr + zjvd",
	"mzqb: 4",
	"cfzw: 6",
	"wjfd: 3",
	"nhhv: hvnt + fdbt",
	"pmgm: 3",
	"gnvg: mrcm * wzmg",
	"hzml: 15",
	"rdhb: 4",
	"hsbl: 2",
	"nqjd: 2",
	"cvmv: 2",
	"mwvp: swbp * jstj",
	"qmww: jtwc + mgfj",
	"fjrs: 2",
	"dccf: 3",
	"qjfq: 18",
	"vpwn: 1",
	"mlhc: 2",
	"vvbg: fccz + tqlq",
	"rpvw: wjvd + ftmr",
	"vrwc: mrzb * jnzv",
	"htqr: hnmg * nsls",
	"mtgh: 4",
	"wbmt: ghsc - drnr",
	"tggl: 4",
	"qfzb: 4",
	"mjjv: 4",
	"mjwl: 3",
	"pzvd: hgjp / ppgh",
	"qngv: 5",
	"qwlh: jzbn - rsbt",
	"jmcl: tpjf + mwbh",
	"dltt: 8",
	"lswp: mpjq + qggr",
	"dmpb: 3",
	"fshg: zzvb * zbbv",
	"llcd: 2",
	"fgpj: 17",
	"ffbr: 5",
	"vndv: 6",
	"wwcj: 2",
	"mbmp: gscn * bsvb",
	"mghd: 2",
	"sbzg: ncqj + tpsz",
	"gmww: sgvv + lhbf",
	"mtcc: 13",
	"hhcg: 8",
	"jbvb: 2",
	"fgzl: 2",
	"wccd: 5",
	"lnzq: mngc * nwzv",
	"hdgl: jbrv * twrs",
	"clvw: 2",
	"hgbn: 3",
	"frmr: wccd + ggwq",
	"jdpj: jcrh + rqmm",
	"hvdb: rnvz * wmpm",
	"fjfc: 17",
	"jcfw: tmwj * hssb",
	"zshs: vwcw - jnlq",
	"nrls: qqgn + vzqw",
	"mptg: tprz * lnsh",
	"gdcq: 5",
	"rzrh: 2",
	"gmnw: 2",
	"mtmh: 2",
	"qgbp: jqsw * lwff",
	"rmpp: sztm * sswq",
	"sqmr: sdwz * htbj",
	"gcfc: qbdg + bjfl",
	"hvsn: 2",
	"djnl: qglt - mcsq",
	"ccmq: 4",
	"vlzj: vsfg + psrt",
	"ffhl: 8",
	"bddf: 2",
	"qwcz: 1",
	"fvmr: 2",
	"ppmh: jlrq + ghbd",
	"qhfr: vcgz * ldjr",
	"cjdj: 9",
	"zcbl: 16",
	"hzzn: 3",
	"pdwn: pvrg + slhn",
	"bdqq: ffjp * pzdh",
	"jvrb: 6",
	"nmvf: 5",
	"stsl: 2",
	"jmdd: 3",
	"nvpg: mqdh * pvsn",
	"dvfl: 1",
	"ggws: 5",
	"whcm: jsjw * snnp",
	"tmrt: 5",
	"rsdz: 2",
	"pfwt: cqcs + vrvq",
	"jqjf: rwwr * lqvq",
	"nwvg: 3",
	"qggw: 2",
	"dsgn: 1",
	"bsjl: 4",
	"wcws: 16",
	"sjsd: tpnw * qghj",
	"lrhf: 9",
	"rbwc: gbwn + mhtd",
	"mggn: 2",
	"zjjc: bshv - whcm",
	"wlzs: rnzz / wqws",
	"qffl: 2",
	"cbdv: bsfg + ptbm",
	"wgtg: pltp * rzsj",
	"mmjt: dfbr - scqt",
	"hvdq: 17",
	"trwd: gcnv * ltjq",
	"vjvn: lrsm + pzvd",
	"scwz: lzrs - dsnn",
	"vdqv: jpqf * hhfb",
	"lgbb: ptdr * wgjp",
	"ftjq: ptfp * zhfz",
	"qtbj: 3",
	"wnmm: 3",
	"tqcv: wgvw + tjwg",
	"ptjr: 3",
	"mhbg: 10",
	"wrlr: 5",
	"blmn: qggw * hshg",
	"sbvp: qqrj + bpmb",
	"nhdb: cgwz / lgfw",
	"gshr: 19",
	"fsvn: 2",
	"bmtm: 9",
	"zbnl: mncp / qjtz",
	"rmch: rwfb * jhnb",
	"cqrn: 3",
	"rprc: dcqg * nppm",
	"mfms: fltj * vmvw",
	"jmrl: mjng * nvjr",
	"lhnm: cbmf * vhps",
	"ffhp: 17",
	"gnsw: 2",
	"mrlm: vfqp * sjwp",
	"bdlh: 3",
	"pjgv: 1",
	"srph: 2",
	"lpcg: rhmc + whsc",
	"glps: 3",
	"grrj: nvvg / gzcw",
	"bcvq: 8",
	"mbnq: glpb + hhqc",
	"nmpq: ttrr + lfzq",
	"jrhp: mrtg + rclm",
	"pnzc: 5",
	"pstq: svzf * nmjz",
	"zbbv: 4",
	"ndbs: 5",
	"scqt: 4",
	"bvzd: 2",
	"fqtc: 2",
	"tqsj: tslh + mrdc",
	"mmqq: 19",
	"lnfh: mddw + twlz",
	"lrnw: ldqv + dpng",
	"ljzv: sbrc * nqsh",
	"rsbt: vdrz * zshs",
	"hjfm: sbvp + wfhr",
	"mhqz: 1",
	"cpmm: 5",
	"dqhr: 2",
	"pdwc: 2",
	"lqhz: 3",
	"zpbc: vstm * dvgw",
	"wsfr: djwr + jddl",
	"pgtn: rshq + scdb",
	"tshn: 2",
	"rhcd: mdgm + phds",
	"cwnt: lvvt + grbs",
	"qtwz: tttw + nfmn",
	"mcnb: lzdj + fqmb",
	"lqml: gmhc * tnns",
	"tdbd: jwgt + mpzn",
	"dclb: 7",
	"qlpt: fwrz * qldd",
	"cshm: 1",
	"zhfb: 4",
	"jsql: 20",
	"ghtl: svvl / sfww",
	"hbsp: cqvn * hdbm",
	"nwsb: tncb + lbpn",
	"smdm: vcjf + lpsq",
	"ltwj: cvqj * jqjz",
	"dqrd: 2",
	"nzfm: 2",
	"lljh: 5",
	"wvvm: 3",
	"gnhc: dvtz * jqhc",
	"svqw: 4",
	"stvr: 3",
	"mmph: 1",
	"zrrj: 6",
	"pfjs: wbfj * vszs",
	"vvql: 4",
	"hwnt: 9",
	"bdtf: drvt * vltm",
	"cvtd: vrvs + pdmn",
	"lcwf: 5",
	"dwtm: qdrh - mzbt",
	"rpmq: nclj + dsgn",
	"dmsl: rdfs + pvfm",
	"wlnd: cntn + thmh",
	"wgpg: 3",
	"gztg: 3",
	"nbhm: qtgq / qfgl",
	"mtsr: btpq * gjrs",
	"vcgz: 2",
	"lcvq: 2",
	"gqbm: qnmw * wqvc",
	"mtpb: 4",
	"mvjq: tdcq * zjzv",
	"zhhf: 1",
	"vspj: 4",
	"mwbh: 4",
	"bvnr: 9",
	"zbll: mjqv + nfjc",
	"sqth: jpvc * mhfl",
	"rclm: mmsw + njfs",
	"lwcw: sjbq * pdlv",
	"pvzl: 10",
	"hdqv: 3",
	"vlsl: bmgf * hndh",
	"bsdh: 16",
	"dndv: 2",
	"cqlr: nmlq * hzwg",
	"twql: 2",
	"wbfj: rgjj + rcnm",
	"gbpw: nszq + cwhq",
	"cbdj: 18",
	"wdph: ghzt * vvlg",
	"vbbc: vspj + mcdw",
	"tsfr: 2",
	"plnt: 3",
	"hnmm: vhbh + rcvw",
	"sqbw: 7",
	"jzcr: vcqm * fwpv",
	"qtjs: tfgl * pbvw",
	"brbc: jwcm * nrvh",
	"mpsz: jcpf + qwgp",
	"cpnv: sljj - zpbc",
	"qghh: vfbv + tdfl",
	"gbjq: zhwq / trqs",
	"crsg: lzvq + dffc",
	"dzcw: cwhr * glps",
	"znzw: 3",
	"gpfw: 4",
	"lwth: 3",
	"cmqt: 16",
	"qrqf: zzhc * zswq",
	"jhbw: mmph + cvbh",
	"jmrn: zcql + pctn",
	"qsvc: 2",
	"pqrr: hdlv - vsmm",
	"tsbd: rjzs + zdlm",
	"snsf: jfjs * pldf",
	"bmjs: 7",
	"mfvt: 2",
	"sdmj: 2",
	"dnbr: mjpj * glwp",
	"bzqr: 19",
	"hshg: 3",
	"jgmm: 2",
	"vgvj: pvwr * srbc",
	"zdmq: fhdn * qffl",
	"dzvh: 5",
	"hfzb: vwrd * bnwb",
	"ssns: 3",
	"prsv: 5",
	"qnjb: 4",
	"fsvl: zpwg + hjrm",
	"wjnm: 3",
	"rqfs: 5",
	"qtgq: nttn + zlhb",
	"vgbb: 2",
	"gtpj: 3",
	"nrvh: 19",
	"vzdv: zhfb * pvzl",
	"lcnc: 6",
	"cmtf: bcmz + gtvm",
	"hzwq: cnhw + fvhs",
	"jqtl: 5",
	"wzjv: 2",
	"plcr: 3",
	"pjrz: jvrn - bvnv",
	"zpmm: 8",
	"hgwt: 4",
	"wchj: pnph * hbvs",
	"bggz: 6",
	"glqn: 4",
	"dvmn: qqqc - dfpd",
	"sdcd: gdbq + gbmh",
	"fthc: 2",
	"gwjr: 5",
	"hbvs: dftz + rsnt",
	"glnr: hjzq * zcfm",
	"zwsg: jtbg * rgfz",
	"hczz: 4",
	"fbgd: qcgf * jzwg",
	"ppgh: 2",
	"npcv: lbvl + cjfm",
	"bqsb: 2",
	"bvrw: chfb * trjs",
	"tqjz: 3",
	"hdmr: pqml * mtpb",
	"dfdp: 5",
	"whgg: 5",
	"wtvf: 6",
	"npfw: wrlr * vscc",
	"rnvz: mgtw * vwsq",
	"qsbw: 4",
	"gmdb: 5",
	"ljvj: vfvb * fqqg",
	"zbgr: 9",
	"nnqz: 7",
	"nhsh: vsgs * pnmd",
	"brgv: jlfv + pwzf",
	"wjdg: ltzz * ddfp",
	"rbjd: wsht - ljvf",
	"hbwt: fczg + mmzg",
	"tvws: 7",
	"ftmz: 4",
	"qctv: nbhm + ttrv",
	"cfdj: dqrd * vzhd",
	"rpdn: dwwr * bpwp",
	"chrg: qbll + dvmn",
	"mhbm: lnsn + ctfg",
	"zstr: 3",
	"tzsh: cqhl * zjsb",
	"fjvw: 2",
	"whcg: 4",
	"hwfn: 2",
	"ntth: 13",
	"zgwc: 2",
	"mfdg: 9",
	"pdbl: dhdl + rnts",
	"rdqg: 2",
	"rjct: 1",
	"pvrv: cbdj + bjls",
	"zwzg: jmvv / pqvc",
	"hsjr: 3",
	"zdbc: 3",
	"mgcm: lpcr * bqcp",
	"sgrq: vpgm + rzsn",
	"jzgz: 5",
	"lwdp: rnqw + rpjr",
	"cjfm: 8",
	"zftr: rwpp + qfrh",
	"vcwg: 10",
	"whzt: 4",
	"pqzc: 16",
	"fvhs: tbfc + hfzb",
	"rnfh: tjsp * tqlw",
	"dcpn: wgsh / cmnb",
	"tcvc: gnsm / fgrl",
	"pdvc: lhfp * hdbc",
	"jngw: 12",
	"hgnl: 3",
	"vltq: rmmp * pbcl",
	"scvh: 5",
	"vgzp: 2",
	"ctfg: nbcc * mnss",
	"hhqc: 6",
	"zswn: 1",
	"gzwr: rvwc * pdgl",
	"ztzh: cscq * pwsz",
	"fgcf: qpvj * vvjt",
	"vhvq: 4",
	"rhzz: cwcv * svzc",
	"bwjn: 3",
	"ffjt: dvvz * bmnn",
	"wgvw: grls * hrmn",
	"jvpq: tszm + mzzg",
	"whcv: 12",
	"zqzg: 3",
	"jstj: qhfr + dqmv",
	"mrcm: fwfn / dlnw",
	"zcqd: cpzd + cwhm",
	"lvpf: lnbd / wbvc",
	"gbjr: 4",
	"fpld: 2",
	"sldd: 1",
	"zzsf: rzfs + nqqb",
	"tpsz: 14",
	"gzvn: wrdv * lmgj",
	"zrts: jjnq + zwzg",
	"zfwm: ssns * bscn",
	"pvcl: 5",
	"mhhc: 13",
	"zzpd: pdfv - mtgw",
	"ndbm: zcbl + vhbl",
	"pfgp: ldvl * nhct",
	"pfnb: gjtj + crsg",
	"lpcr: 3",
	"nwpg: 2",
	"pmsv: lhqc * glrq",
	"vmgl: 3",
	"qtfb: 5",
	"lzqf: 19",
	"cvgl: rsvd - tvqh",
	"fccz: 11",
	"zcfm: vdsw * mwbr",
	"wljf: 5",
	"rnwc: dnbr + rmrf",
	"jpdf: 2",
	"qtvf: lmsr + vrjc",
	"zwdl: fcwp + whvw",
	"sscv: tnrq * zbll",
	"jvrn: ltjf + brgv",
	"bvtc: 2",
	"rvwc: 5",
	"ncrq: wlgb + ggjw",
	"snvs: 1",
	"wggc: zqrj + wmzl",
	"rzsn: nqtb + qrdg",
	"prrv: 2",
	"rmrf: vmjb + qgcr",
	"lbvl: qmwp * mjwl",
	"nchm: nhsp + vtts",
	"ggjw: mchm * mhhc",
	"jzbn: hwzw / jrss",
	"cvlv: 3",
	"lztz: fbgd / mwtr",
	"gdbq: 5",
	"ddrm: bjbh - tpmw",
	"jqbf: gbpw - ppnd",
	"wlsp: jcgp * pdbl",
	"ppqt: vmnj * cpgd",
	"tcqt: 9",
	"fntj: dwlp + sscv",
	"jsrw: dzcg * mqht",
	"nwlv: 2",
	"qjts: 2",
	"mnfl: pnbd * fdgj",
	"bsdz: zghm - zfwm",
	"zwhw: qcsv * rfll",
	"hlgs: rnwd * qvch",
	"dwnr: 8",
	"ntmm: fjvw * jdpj",
	"bnql: wnlc / qmbb",
	"pllq: 15",
	"hmld: 8",
	"slnt: 11",
	"fwfh: 3",
	"hsqw: 1",
	"ptwl: 3",
	"rzsr: 4",
	"nsls: 5",
	"pwfs: pfjs + srhc",
	"jjvt: 5",
	"rndj: 3",
	"nhbd: 2",
	"lszd: rzcl * mbqd",
	"fhzz: 5",
	"qghj: 6",
	"svfj: 14",
	"jdqv: 5",
	"tmrb: 3",
	"nnmz: 5",
	"nqqb: nwsp * trnl",
	"ffbp: zczj + nmvf",
	"lcqd: mvds + zzgt",
	"qgdg: 4",
	"qbll: 3",
	"jvsc: 2",
	"cnwj: 4",
	"tjqf: lqmt - zswf",
	"zbht: wttr + qwnc",
	"stws: 6",
	"gqtc: fcmh + nhwq",
	"jtcv: 3",
	"vzhd: 17",
	"pqml: hvbh * gjfj",
	"sbrc: 3",
	"nzdf: 18",
	"cpzd: 14",
	"bgzp: cvsf * hwfn",
	"gplf: 2",
	"ldjr: qjlf * fjrs",
	"pntz: 11",
	"nfgh: shhw + zngb",
	"mstp: nndq + rmtl",
	"hrmn: 7",
	"fqmb: vhvg / zfhv",
	"pdjb: nfcm * gvnl",
	"rnzq: 5",
	"wwgq: 2",
	"grcd: qjts * dmpb",
	"rfgq: pldl * ndcb",
	"tqph: 2",
	"cvbq: dbmc - zwhw",
	"prcr: vlww + hgnd",
	"djfq: 3",
	"hjrm: qfdg + rdjq",
	"llcz: 2",
	"vrvq: hsnr + fgpg",
	"ghcz: 7",
	"ccrf: 5",
	"clvh: 13",
	"bpqc: dnzg + czdm",
	"ngpf: hptc * mrrf",
	"cmgn: mtsr - srpj",
	"vgll: zrts / hfgh",
	"qrlv: sqvv + vlql",
	"whhv: mzqq / zpjw",
	"gcvv: 4",
	"rwfb: 4",
	"dgbq: 13",
	"zjsb: 3",
	"gzvj: wbzg + wgzd",
	"stdm: hvsn * dgvq",
	"pvnb: 5",
	"zghm: rlvz + wfcv",
	"ghbd: frmr + lfwr",
	"hfgh: 5",
	"cfls: fcdr + ztpj",
	"wtst: 2",
	"qnhf: vggm + vltq",
	"smvr: 13",
	"mblf: hjlt / rlcw",
	"pdmg: mgcm * sdjq",
	"jgbs: 3",
	"psrt: 3",
	"fwrz: 2",
	"blqb: zdbc + trtr",
	"hcnj: htcn - hczz",
	"lwff: vwpt - bcwc",
	"gnsm: srhh + szrq",
	"dgct: 4",
	"lpsl: sqmr / pgjb",
	"prdg: jjvc + lqlg",
	"sfdh: mvqq * rbwc",
	"pqvc: 4",
	"hrwt: 13",
	"vrtf: hbdw * qtdb",
	"fcmm: ffhl + nnmz",
	"vpsv: fwtf * qdhd",
	"hdqs: 1",
	"tmzh: rtgt * wpzv",
	"ldhv: jrrb * gqbj",
	"twnj: qpzl * cnll",
	"ddfd: 3",
	"mpqs: lbhm * htqr",
	"szlh: 2",
	"sfww: gfpj + pgzj",
	"zfmq: 5",
	"fcfl: 2",
	"fzwz: 10",
	"srhc: mpjh * splf",
	"chfb: dwtm + slcv",
	"vrzh: lnzq * fcgt",
	"cvsf: bcsn + sqvc",
	"fplv: 17",
	"sqlb: smvr * slsq",
	"nncl: lwjp + lwlj",
	"fmrp: 3",
	"gqlr: nnbq * rwpt",
	"zwsb: pwct + wmmt",
	"twrf: pllq - gggv",
	"gcvl: 3",
	"wslg: 4",
	"njrm: 19",
	"lwwn: wtfc * vscf",
	"fzlq: wjqs + jmvs",
	"root: tlpd + jjmw",
	"trjs: 2",
	"srcd: 2",
	"dpgq: 17",
	"rzlz: 6",
	"wsfn: 2",
	"wfzp: 3",
	"qvch: 2",
	"lqfr: szvv * btrg",
	"pznd: shds + dsgr",
	"shds: 6",
	"qdhd: 2",
	"wggm: ljdz * nhns",
	"vhbm: 4",
	"wsvp: 5",
	"rgjd: 4",
	"rdtm: 2",
	"rgmg: zbgt + rnwc",
	"lvbg: 1",
	"ndgs: lpld * zhhg",
	"fdbd: 5",
	"mgmc: mrwt * mvtd",
	"zfdn: pgmt + nchm",
	"rqdj: 10",
	"sccz: 4",
	"pbfc: 12",
	"vgzc: pprl + vbgd",
	"dvgw: vqcc * ddnc",
	"wldb: 9",
	"czdm: cvgl / nnfh",
	"vrbt: 4",
	"mwtr: 2",
	"hgjp: whqz + fqbz",
	"hhnq: vrfl + wgcp",
	"svcr: ccfg * fjnb",
	"nblf: 3",
	"zwlh: gwdp / stws",
	"nvvq: 2",
	"jtbg: bvcj * lsqf",
	"mrdc: fbvv + mmjt",
	"lpsq: wcgt * vgzp",
	"ddvm: 2",
	"mlpn: 2",
	"ffdp: ljhd * rldb",
	"bncm: fmgm * mrhn",
	"zbgt: wqbz * mbjr",
	"rgfz: 20",
	"hpls: 3",
	"hzwg: 2",
	"gznm: 8",
	"rwpg: jpbw * dsrt",
	"hsjd: plcr * hgwl",
	"mmzs: mcfd / gptq",
	"mcfd: qdbn * rwnh",
	"nvbl: 2",
	"mpzn: dndv * vbqg",
	"plzn: 3",
	"csht: pgmp + sbsz",
	"ztfz: 3",
	"rvlh: bjhn * zgcr",
	"rljh: hbsp * whqv",
	"gmdz: rndj + lpsb",
	"jqhc: 2",
	"bdst: 8",
	"ccrh: ltrm * vclf",
	"wmmt: rpdn - qtvb",
	"cqpv: jfpd * mvtf",
	"wshz: lnsr * thnr",
	"rsvd: bmvr / hhwb",
	"stqj: 3",
	"lhlc: vtbv / bdst",
	"slcv: ddfz * hbnz",
	"qscg: bfvn - bhwh",
	"dvhc: 12",
	"nndq: 11",
	"hmtz: 2",
	"ljhd: 5",
	"fcmh: zrrj + vswd",
	"bwgj: 4",
	"cblt: 2",
	"ljdz: 2",
	"bjln: zbnl / lqhz",
	"wzsr: 6",
	"bpfz: 2",
	"jslc: msmz - lgqq",
	"rdsp: 2",
	"ddgp: 1",
	"hmpb: 9",
	"qdsj: zjzj * jgmm",
	"qgqf: hgnl * cnrm",
	"gwjn: twnj * gtfs",
	"qdrh: ghgc * sjzd",
	"jwpb: 5",
	"vcqm: 2",
	"rfpp: ldzh + pjqw",
	"rtmc: znnt + jnvd",
	"hpsz: 6",
	"drhz: lpzh + ptqg",
	"dsrt: 17",
	"hhll: wndb / hgwt",
	"fhrp: lmsc + lspz",
	"bhvn: 2",
	"lfgq: bzcw * rdvt",
	"rpqg: bvwj + pclv",
	"fbhv: wbht / chbb",
	"cpmc: 3",
	"gldl: 3",
	"nfvj: 3",
	"hqlv: wsvb * rgfm",
	"zjzj: 3",
	"bvcj: wjnm + chrg",
	"svlb: vcld + qrfb",
	"bshv: gfzz * tcbb",
	"dvzq: 2",
	"lzvm: bzmw - hzml",
	"qcgf: mdsd + nctp",
	"gptq: 5",
	"glpp: 8",
	"zgms: 8",
	"dvtz: 6",
	"vqvn: qpzr + bwmz",
	"qvmz: 5",
	"jznb: dqfj - jnjt",
	"jtwc: ncrq * gmnw",
	"shjf: lrnw / dgzb",
	"lzwf: 5",
	"lqjw: 2",
	"vgch: jsgj + ffpb",
	"jnbr: 5",
	"vlbt: 2",
	"ljvf: brbf / rcpt",
	"fzrq: slwl * qcsp",
	"tlvf: qwdg * nqjd",
	"hffn: 2",
	"qlvv: vstp * fmvn",
	"nhtj: 10",
	"sptm: 2",
	"bwhg: 3",
	"qjtz: 3",
	"cnhw: rzbj * fgfp",
	"cntn: 12",
	"thgj: 4",
	"hhbp: wqht - ljzv",
	"fnhg: 15",
	"hmhs: 8",
	"bptm: 3",
	"tvjw: dhts + vccm",
	"jrpf: 2",
	"wmqq: 5",
	"tmnj: flbd * svtb",
	"lvpg: 2",
	"rwnh: bwgj + rsqv",
	"wstd: 2",
	"fjnb: 2",
	"scnp: 2",
	"flff: 2",
	"tdcq: 2",
	"tbzq: 5",
	"fjqs: hblz * nwpg",
	"lnbs: crvh * wglp",
	"jddl: cfpg * trwd",
	"sggr: 2",
	"bsch: 2",
	"tnqw: mqrz / pdjb",
	"phmw: nzsw / qvmz",
	"hbhc: 6",
	"dssj: wdnd * lzrm",
	"vrrl: 2",
	"wdlv: 12",
	"pngq: gpcv * bzzz",
	"vsmm: qrvb + wjfd",
	"pgjb: 2",
	"swmb: bbfz + nfbq",
	"dhts: dvhc * ftsd",
	"svbl: 1",
	"wvcb: 16",
	"rwmn: zngv - ggnb",
	"zrbh: lsdf / rndv",
	"ndpl: 2",
	"dfgz: 2",
	"rzfs: dbqj * rbtj",
	"ngph: nvlr + cmgn",
	"ztbf: 2",
	"qgdr: 2",
	"fhct: 17",
	"tvqh: wntr * rzcj",
	"bhwh: 4",
	"mchm: pnjw - lzwf",
	"dwwr: 5",
	"jfjs: 4",
	"vzcd: mtgh + nvjg",
	"hsrb: nlrm + zjnz",
	"cfqd: hpsz + gtgs",
	"bpmq: 5",
	"hblz: 9",
	"vstm: vgbd + ttdf",
	"cdjg: 7",
	"dcqg: qfbn * hmht",
	"mbst: zwlh + sgrq",
	"pbzb: lbhz * jvzb",
	"svzf: 4",
	"rvlw: 2",
	"hdlv: vfhc * wsvp",
	"sztm: 2",
	"wdgb: znvn / wwcj",
	"tslh: rzmw * wtvv",
	"wmpm: 2",
	"rqqn: sqzh + stsp",
	"jcjg: jhlh * ppls",
	"rqcp: vrtf - lwdp",
	"fztd: 2",
	"qghl: 2",
	"tnnr: wdgb + ctnm",
	"qfcc: cggm + dqzh",
	"qlzq: 4",
	"gcnv: rmwh * rbvw",
	"rchb: 2",
	"tghz: 2",
	"wprq: mfsl * tjfh",
	"jrpl: bwdq * rlsl",
	"zjqg: lpsl + lgbb",
	"rdhf: hfnt * sdmj",
	"fdnz: vtcz * njfh",
	"qhrc: hlll / rwbc",
	"fmgm: mblf + grrj",
	"fcwp: 6",
	"mwtg: cnwj * rfpp",
	"bmgf: sbqw * srrj",
	"fvsq: twjj * tstc",
	"dlnf: 2",
	"mpzb: 2",
	"lmsc: nhdb * hjll",
	"dgbb: 2",
	"pvtn: tmtc + cjdj",
	"vfjs: schg + bdvr",
	"cvbh: 16",
	"ppnt: vqqr + npfw",
	"fhtj: 3",
	"thwc: hzzn + hzll",
	"bjfl: pvtn * hpjw",
	"tspj: tdqt + ggwf",
	"qcgq: vpfs / scnp",
	"rrmn: lchl + mmzs",
	"brzm: 4",
	"mzmp: ltft + mlmz",
	"gbjb: 9",
	"wvvt: sjpr + gsjn",
	"mjjc: 3",
	"whqz: qbdb * nnqz",
	"ccfg: 10",
	"cvmd: qgqf * zvtl",
	"fsjs: 5",
	"vsfg: 5",
	"fhbm: fcwq / rzlb",
	"prnh: 11",
	"hvnt: mwjj / dgfg",
	"tpgn: fhzz * njrm",
	"wmgw: rmcb * srph",
	"pvwr: 3",
	"zzcb: 1",
	"cflr: qqjv + gtlr",
	"mplg: 5",
	"bmnn: 3",
	"ffhw: 4",
	"vqsl: dfmb * dgnc",
	"vpsb: pbfc + vnvn",
	"ldrw: jgvq - vgbb",
	"pznr: fvsq + zlhz",
	"fggl: tqzc * pnzf",
	"mfmr: 2",
	"ghzt: 13",
	"vmnj: 2",
	"pqhm: 2",
	"rlvq: 2",
	"jqvm: 3",
	"cglq: pjrz * pdpv",
	"cfsj: smpt + gmwm",
	"nzsw: czrh - gzwr",
	"lptm: nglh + rssz",
	"fnbw: qqnp * lnns",
	"ncqz: 2",
	"dgfg: 2",
	"tjpc: 3",
	"rjjc: 9",
	"jpvc: pzjg - mgsm",
	"snnp: 6",
	"psmp: 6",
	"fsmh: 2",
	"bczv: qthd - tzrc",
	"hlhr: 3",
	"rwpp: 14",
	"qfnl: bczv + wbrf",
	"vzqw: jmhz + bzqr",
	"rfvj: bpfm - qpdf",
	"mlmz: hmhs * hgtf",
	"pszn: 20",
	"jncd: zwdl + zfdn",
	"wvzs: jgjw + ccmq",
	"jcnw: blqb * thlr",
	"gzhc: dwcw * qfnl",
	"nbgn: bcvq + lvwf",
	"wsht: czmr * bhvn",
	"qpzl: 4",
	"zhth: 3",
	"wlhb: 1",
	"njfh: 3",
	"vstp: 4",
	"hqsd: 4",
	"jgpj: 15",
	"tnwg: 3",
	"rgnq: 3",
	"fqbz: 8",
	"ncqc: 5",
	"gwjs: 2",
	"hgmq: 1",
	"mgbb: hfwv * zhgp",
	"zssp: qfdq * fjlj",
	"htzp: 2",
	"cnst: 3",
	"zcwm: sttz * jlpn",
	"tjqb: vjvd + fsvn",
	"jjmw: tsbg * ndgs",
	"tnns: 2",
	"jhnb: 6",
	"hssb: hglf / sshq",
	"gctz: 3",
	"lvmv: 5",
	"ptbt: 3",
	"zlpf: 2",
	"btng: 2",
	"lhdg: 3",
	"qqnt: wvvt + mztf",
	"mrtg: thhq - ddpt",
	"ttdf: 2",
	"vcdj: dspv + hzrb",
	"tstc: vmwn + smcp",
	"wjvd: jfdb / cgdp",
	"tbzl: 2",
	"cwht: wrrp * mvsc",
	"wrzd: 9",
	"pgmp: 2",
	"vnsw: mpsz * nqwf",
	"hvtm: nbgp + wldb",
	"vwcw: sspw * blhb",
	"vrdm: 3",
	"lmsr: gdcq * trfc",
	"qwdg: 4",
	"bsbt: lnfh * hfvc",
	"sbtp: wshz + nczr",
	"htbj: nmtf + cpnv",
	"nprf: rmnj * nhrq",
	"gcdm: 1",
	"fsqj: thqq * jqjf",
	"zfhv: 2",
	"vsgs: 2",
	"cwcv: 5",
	"vnnz: wnmv + qhcw",
	"nbgp: 8",
	"zpnn: hcqq / rmfr",
	"schg: nnhd - mmbj",
	"zjzv: 15",
	"tnvw: 2",
	"jsjw: fntj / pgwz",
	"jwht: tdhh / fqvr",
	"fclc: 3",
	"lnsr: lzfv + ztqv",
	"jjbt: rpbs + rvlh",
	"qltr: 5",
	"vvlg: 3",
	"vccm: pnrq + lzqf",
	"vltw: 3",
	"qqnp: fjqj + mfjs",
	"znft: zpjz + gmdz",
	"vmwn: 2",
	"znnt: srjj * fgzl",
	"hhwb: 3",
	"zjqd: nfjz + dpvh",
	"qlnm: 3",
	"jzzd: vzcd + rrtm",
	"fftd: 3",
	"qwnc: pfpd * gzlb",
	"jgvb: 2",
	"wtfc: 2",
	"jnvd: 9",
	"hwmj: rnfh * dtpr",
	"hcqh: 5",
	"ddfp: wljw + phql",
	"lvvt: 7",
	"vrfl: tpgn + wgtg",
	"dbpl: 13",
	"bmdw: qmww / mbms",
	"rjnr: 3",
	"wvrl: gwcv + hhdz",
	"qfdj: 7",
	"bsdm: pnlb + wzzg",
	"rbtj: tgzb * vnfd",
	"zbvz: lcbj * rjlw",
	"tthp: 3",
	"hglf: 12",
	"vnph: 2",
	"znrp: 13",
	"zlhg: 1",
	"tcvf: pnhq + gwjc",
	"szlg: 1",
	"thhq: cvnd * pqgw",
	"wfcv: clvw * fhct",
	"zzgt: 12",
	"rmtl: dvnl * dnml",
	"cvcr: 7",
	"vdtc: 3",
	"szjw: dvwf + mnbb",
	"cjnl: qblm + tlhm",
	"vcjf: 1",
	"sshq: 2",
	"gghf: 3",
	"dbwn: 3",
	"fchj: 3",
	"wbht: tcvc - nrpg",
	"mfjs: plsn / ncqz",
	"tbqb: tgzh * hbfw",
	"nmjz: 3",
	"cffl: bvms + jvbq",
	"hmqm: nftb + gpbr",
	"swns: pzcv + psmp",
	"cgdp: 2",
	"zvjn: pwcd - tvqb",
	"bdvr: 3",
	"tbpn: fdnz + nhmp",
	"pdzp: 3",
	"gbqd: 3",
	"ghgc: tzdz + gbjr",
	"mrgj: 3",
	"qttn: 2",
	"qpwg: 2",
	"thlr: 3",
	"rsqv: nrdd * hsjd",
	"ghbs: 20",
	"rpsg: 1",
	"ctcq: 3",
	"dlln: nwlv * vpsb",
	"hcmm: jjhf + rczq",
	"tfqz: 2",
	"njbz: pfgz + hrwt",
	"wbzg: 18",
	"mwnp: 15",
	"zwqp: rjnr + lpwm",
	"cgmc: fzdf + thwc",
	"hwwf: 9",
	"nztf: 6",
	"pnqr: nqnb + rlqd",
	"qtdb: 20",
	"vbqg: sbwr - rjct",
	"nlzg: tvzf * bncq",
	"dzzd: fvhq / nlvv",
	"bnwb: 3",
	"pprl: 5",
	"ptfp: 3",
	"qhqz: rnzf - sbpm",
	"wdlz: hjjp + jddv",
	"jphb: 2",
	"thmh: mtzn - ffch",
	"hqcc: 6",
	"dvnl: 3",
	"nrcv: pqzc * gsmr",
	"qthd: rnbd * vswr",
	"dhmq: zmhz + hbsb",
	"djjq: gljq * jgvb",
	"ldpn: zbwp + sglw",
	"dnpp: 5",
	"lcbj: 2",
	"zbsh: sjsd / cfzw",
	"jlpn: 11",
	"dbqj: 2",
	"dmbb: 2",
	"cvvd: vgwv * vfhv",
	"gtld: 5",
	"sspw: 9",
	"rzbj: rljh + lhlc",
	"vtcz: blvw - gwqw",
	"swnm: jgbs * dhmq",
	"dspv: bnql * jgdc",
	"dvwf: lwrv * jvdq",
	"rlnv: ztfz * wnmm",
	"jcgp: gssp + gjdr",
	"gscn: 3",
	"cpgd: humn - mplb",
	"lchh: qrfc + mfmr",
	"tlps: vsgc * nwvg",
	"ctjf: 3",
	"mpmh: tvqc + zfmq",
	"gwjc: pnzc * lnwv",
	"wfgv: zzfb + vpwn",
	"twsv: qrzm * rzrh",
	"lpzh: 3",
	"bzmt: qrqf / vrrl",
	"mcdw: 9",
	"dtpr: 2",
	"pdpv: 3",
	"mwcz: sjnv + zjzq",
	"qblm: zfwq + zgzm",
	"qbdb: 2",
	"hjvv: 10",
	"tqvn: vnsw * vspl",
	"wqdp: 2",
	"gtls: 2",
	"qdhv: 2",
	"zwzq: gznm + dbcz",
	"mrbb: bbfs * vrbt",
	"jvzb: njjj * lnpt",
	"dsng: pgtn * dvcv",
	"nqwl: 3",
	"njmb: 7",
	"rvwz: qzjn * zjqg",
	"cphh: hpqn + njbz",
	"pzzl: wnmz * qjlj",
	"mzng: cgsb + lrhf",
	"jjhf: tvsl + lvbc",
	"qcvn: 7",
	"rdjq: 2",
	"lrbw: glqn + wfgv",
	"szrq: bvzd * scwz",
	"cqzg: fgzg + pgmg",
	"wlpf: gtmt + mwqh",
	"tpwj: cfsj * sqsq",
	"qfdq: 5",
	"zzvb: qglv + hmgj",
	"wrlt: 3",
	"jcrj: 5",
	"hmlt: fpld * wpvf",
	"mshj: 3",
	"dfmw: mnvc + qttn",
	"ncwd: fclc * lbhn",
	"lczp: 16",
	"jfdb: 12",
	"mmpj: wvrl - blgh",
	"gtss: 2",
	"vzhf: 4",
	"fsfh: 5",
	"bvms: 9",
	"ltjq: zmgh + qjqz",
	"nttn: 5",
	"slrh: 10",
	"dqfj: 12",
	"fswz: 5",
	"pnrq: hzhv * qgdr",
	"lmgj: 3",
	"llbz: sptm * blzm",
	"zgsv: 3",
	"vwjq: nvrc + bmdw",
	"tvqb: 4",
	"jpqf: 3",
	"tjwn: 4",
	"ljmt: 2",
	"wzzt: vvql * vhsj",
	"cndf: 2",
	"srjj: jsbw / nhnd",
	"qhwn: 5",
	"vwsq: jqtt + fpch",
	"srbc: 2",
	"qzjn: dvll + jspc",
	"cwsw: 4",
	"zgsf: 7",
	"fbvv: 8",
	"nmhh: djzw * fqfw",
	"wshg: 5",
	"pbtf: hsrb + ptch",
	"jfcq: 3",
	"srrj: 6",
	"tmqv: jqjr + bqsm",
	"ltlg: 8",
	"lbhn: 2",
	"nnhd: vdtc * llpw",
	"pvrj: mlhc + hznp",
	"sqvv: rgjd * lddb",
	"pmbz: dgbq * lvpg",
	"hfnt: slrh - zzhz",
	"wsfp: gldl * pznd",
	"bsfg: 5",
	"gtmc: ljhv + dmvq",
	"nhwq: 3",
	"rmfr: 2",
	"fhdn: tbgc + mpqs",
	"fbvf: prnd + vsww",
	"hbmw: 4",
	"bgcc: zswn + pngq",
	"rjpv: 2",
	"mvvb: phmw + jcwd",
	"ztvd: rgdb + stwm",
	"cghg: jggn / bpzr",
	"vhsj: 6",
	"lbqd: 2",
	"spjv: 4",
	"tbht: zdmq + wgrl",
	"wplj: 5",
	"crvh: 3",
	"wccg: lmjp + dbwn",
	"vcql: 4",
	"ftns: 3",
	"gvbq: zsjl * jtcv",
	"zrtl: rqdj - nfvj",
	"ccpv: nvvq * mbfw",
	"wpvf: wfgr + pqdd",
	"nqsz: tspj / dwwp",
	"sgvv: stqj * gdrh",
	"ppnd: 13",
	"ztgc: 13",
	"wmpn: 2",
	"ltrm: jgnh + zlcf",
	"dhcf: 1",
	"cnll: 4",
	"bbbd: vlzj + hgql",
	"mnss: 8",
	"svcj: cljg + vvbg",
	"ddfz: 5",
	"dfpd: 2",
	"nrtn: ngpf + lwrz",
	"trnl: 3",
	"ddnc: jwpb * ssrc",
	"cwhr: 3",
	"tmtc: shnm + tpsr",
	"mcqb: wsfr + hfjr",
	"vszs: 2",
	"lwfw: 5",
	"phpd: rvdf * wfcs",
	"fqqg: 7",
	"stnq: dpzf * nzdf",
	"fqfw: 5",
	"zlgj: pdsl * njwn",
	"bsnw: dnpp * srcd",
	"qfrp: wqmw * djfq",
	"tghv: 2",
	"pvfn: 2",
	"tbzj: zzpd - tmnj",
	"qwgh: 14",
	"cttz: 2",
	"rttw: zrzj + fmml",
	"slwl: 2",
	"bmdd: lpbj * fjjn",
	"qrzm: 13",
	"wjnz: 7",
	"zzhp: dzvh * msjt",
	"ghfg: zgsf * cfhv",
	"rdfs: 11",
	"jcrh: ztbf + flnw",
	"grfq: vjcm * mcnb",
	"twjj: 5",
	"prhf: 13",
	"ffch: 3",
	"jgdc: sdzc - cghg",
	"qmbb: 2",
	"rvtg: svbl + pjch",
	"hznp: 5",
	"rjmp: lcwf * vnnz",
	"mwrv: mnfl * cbdv",
	"vscf: 3",
	"mbfw: 4",
	"vclf: 2",
	"mddw: pjmq * cfnc",
	"dqmv: bwjj + pwfb",
	"qpdm: 6",
	"ctmz: rjbd + jjbt",
	"nhnd: 2",
	"pmlg: 16",
	"rdjr: 17",
	"lwwv: 2",
	"hvtd: 4",
	"hchr: rsdd + gcvc",
	"jnlq: shvc / dltt",
	"hcqq: rpvf + hwnt",
	"dnml: 4",
	"vhbh: jmft + jtwb",
	"rsnt: cvrf * pqtl",
	"scdb: lcvq * qmgv",
	"gsfp: fmqq + lqjw",
	"ccrc: 2",
	"vjvd: zrgp * dlfv",
	"ffmd: 1",
	"vsrr: pztl * dbqz",
	"bcsn: nzjs * bpmf",
	"pzmt: rvtg * cfqd",
	"hqjp: pnnr * fthc",
	"zngv: nrlh * clhm",
	"htcn: zzms * dpbz",
	"qqgn: rswb * jngw",
	"hcmb: mgbb + lmdm",
	"vjdq: fnqs * rzhg",
	"shbg: fnmw * zqvb",
	"jfrw: bdzd + fzlq",
	"vgbd: gbjb * bptm",
	"cgfd: 16",
	"ggqp: 4",
	"cscq: 2",
	"hqrp: 3",
	"wgzd: jrpl + cvvd",
	"flhf: ghbs * tnvw",
	"rmcb: whcv / vmlj",
	"fthj: 8",
	"lgfw: 2",
	"phds: 1",
	"lvbc: 1",
	"mmzw: 2",
	"pnff: 3",
	"zlhb: phmr * qdtc",
	"jmvs: tthp + spjv",
	"dlfv: 9",
	"dwmt: 2",
	"hdpb: wlnd * rjpv",
	"wtbp: 9",
	"vwrd: bzts / qdhv",
	"jzql: 7",
	"bpqq: tbzj + nqvm",
	"mqht: wtlw * qltr",
	"rczq: 8",
	"dntp: 4",
	"nptq: jncd * swqf",
	"lpld: fsnh + cldc",
	"wmwb: 9",
	"bmvr: vrjg - cjvl",
	"lzgz: qnms + wvjb",
	"mwqh: bdtf / fbcl",
	"bvsb: zshh * lzmd",
	"phdw: fhhg + tghz",
	"bqsm: 8",
	"bbrq: dpqh * fjlz",
	"vlrl: rlcr * mwrv",
	"fmvn: 8",
	"qpdf: qwlh * jhld",
	"szzh: 11",
	"gpbr: 6",
	"jjnq: gvwd + pnhb",
	"jvbq: mpsj * gzbz",
	"zzhw: 2",
	"tvcf: 5",
	"cgps: 3",
	"phsj: 13",
	"mzqp: 3",
	"fcgt: 2",
	"tzgc: ldgc * npwd",
	"lddf: 2",
	"ddsb: 5",
	"qglt: 10",
	"fldl: cfdv * vltw",
	"lldm: 2",
	"sjbq: 4",
	"wrrp: 7",
	"lwlj: zzch + hqsj",
	"pddw: fldl / qbhh",
	"btpq: 7",
	"hrbg: 2",
	"wfhr: jrbb * fsmh",
	"zpct: 2",
	"qwdq: zwqg * wzjv",
	"nrdd: 3",
	"wmlm: vlhj * hsjr",
	"zhmp: 2",
	"fcjb: 4",
	"jqjz: gtpj + vgvj",
	"stmf: 3",
	"lbtb: pzzv * wmpn",
	"wjnn: fvmr * hvtm",
	"jcpf: qlqm + mrnn",
	"mrzl: 2",
	"pnhb: lvpf * gzsb",
	"nwzv: 5",
	"rbvw: 2",
	"bbfs: 11",
	"tlrz: 3",
	"dgvq: 3",
	"glmc: 2",
	"fhhs: 3",
	"pttq: fhhs + glmh",
	"shvg: ftml * ggzr",
	"vsts: hcmb + vlrl",
	"mgfj: zbht + vrwc",
	"mrwt: 5",
	"tcnh: 9",
	"ntvs: 11",
	"zttz: qccz * hlvb",
	"pbsg: brrp + zhth",
	"wdbm: 2",
	"gdnd: 4",
	"lgth: 12",
	"dfch: bgjq * pwbd",
	"jtwb: ztvv * fcjb",
	"vfqp: glpp + bmtm",
	"mhtq: nblf * cqrn",
	"rtgt: 3",
	"vfcg: 3",
	"pbcl: 2",
	"ptbm: 1",
	"qtvb: mmzw * rhzz",
	"fjhd: 2",
	"tncb: hcmm + zghz",
	"rnzf: lptj * zqtp",
	"pnph: 7",
	"tdlf: 2",
	"vcst: 3",
	"cqcs: 5",
	"tpsr: phdw + cprz",
	"wtlw: 2",
	"pnnr: dvbm + vfsz",
	"lnwj: 2",
	"qggr: jfrw * rttw",
	"vfbv: bmhq + lcgw",
	"rnts: 4",
	"tbcf: ffhw * jdqv",
	"qfbn: rsrt + flff",
	"lwrv: ghld * wcmt",
	"ccdm: wjwb * ttbz",
	"jnzv: 4",
	"jbcl: 7",
	"vswr: 7",
	"psmh: 2",
	"brfq: bsnw * wljf",
	"rshq: 5",
	"zjzq: ftns * dgbb",
	"wcgt: 3",
	"vscc: 17",
	"tszm: mjfm * ljcq",
	"tvzf: 3",
	"tvdm: wggm * tbzl",
	"jwcm: nfsr * zvmn",
	"tqlq: tgfr * rnhv",
	"lnsh: 2",
	"rhhm: lwth * qvcv",
	"rppv: 4",
	"nhbh: tjpc * pdhb",
	"trtr: 5",
	"pnhq: rbzn - qwdq",
	"wrmc: 4",
	"tgfr: 11",
	"qdtc: 3",
	"qrdz: 7",
	"dfdq: crwr / cvtd",
	"bqcp: 8",
	"crgq: 6",
	"ldwz: hwmj / smhn",
	"zwmn: bbhr / cndf",
	"gnbp: jpqn + hmzf",
	"tlpd: mzmp / fqtc",
	"bzts: bvsb / tdlf",
	"brrp: 20",
	"nwwt: 2",
	"ffct: 2",
	"sjnv: 5",
	"tjnn: 12",
	"grbs: 2",
	"tcbd: mfms + hqlh",
	"bmwh: 2",
	"gzgp: 5",
	"jwfc: 5",
	"rgsj: gqtc + ccpv",
	"dmvq: wvvm * zbgr",
	"ccrq: vjfs * wdph",
	"rzcj: 2",
	"wwjp: rvlw * zdll",
	"jjvc: cqth * rnth",
	"pgmg: mwtg / wzwl",
	"cbmf: dmbb + vlqj",
	"znvn: gnvg + ppqt",
	"jrbb: znrp * frzv",
	"ghld: zwsg + swnm",
	"zbwz: 3",
	"nhct: 4",
	"stwm: nhbh / znzw",
	"lnsn: bqzr + vcqr",
	"sdzc: ctmh * vgch",
	"rzhp: ggqp * nvnv",
	"qhcw: 2",
	"flnw: 7",
	"bqth: 2",
	"sbpm: lqfr - fggj",
	"twrs: jspg - pbzb",
	"rrfz: 9",
	"nqwf: 2",
	"ndpr: sstc - dfdp",
	"tvqc: 3",
	"bjls: 13",
	"fjlj: 2",
	"nftz: 2",
	"hpqn: mdff * sfdh",
	"dnzg: pngd * ldpn",
	"lwjp: hdmr - nmhh",
	"rjbd: nbgn * stmf",
	"hwzw: vdvq + vsjs",
	"cvlc: hdpb * qqlp",
	"cljg: 8",
	"gzsb: bpmq + tggl",
	"zzch: dbpl + wjnn",
	"vltm: nqsz + dscr",
	"pqdd: 19",
	"fwwg: 19",
	"vgpd: pbwv + gnbp",
	"ldvl: 7",
	"lmzz: lsgz * pccm",
	"bqcb: stdm + mtcj",
	"bmcl: 2",
	"njjj: 2",
	"cttp: 2",
	"hjhh: zglm * vtbd",
	"fczg: 6",
	"dwzg: 1",
	"qglv: rvwz + tbht",
	"pdgl: hzch + jgrl",
	"wqws: 2",
	"vhps: 2",
	"ghpp: bcrl / bddf",
	"jbdw: 2",
	"shvc: fbhd * qgdg",
	"mjqv: 1",
	"qzrz: 5",
	"rnwd: 12",
	"gmqb: 10",
	"wllb: dltv * gcvl",
	"jjnw: hhpt * gqqr",
	"mtgw: 15",
	"lpgl: 2",
	"cbgs: rjzg + jzcr",
	"jzrn: rpvw - fvzc",
	"hswq: 3",
	"qbhh: 2",
	"tfgl: 14",
	"gwdp: hjfm * vrjh",
	"bdzd: 3",
	"ptwc: 2",
	"tpjf: vhbm + tcqt",
	"fcdr: 4",
	"djmv: qmdn / nzfm",
	"vchc: wllb * bsjl",
	"zlhz: rvjp * wdgh",
	"sqsq: 3",
	"jtrw: 13",
	"gwqf: rfls * mcqb",
	"rpbs: slnm * hwwf",
	"vrjh: fcmm * hmld",
	"zrzj: 2",
	"jbjm: 3",
	"nnzr: 17",
	"brbf: wjdg * gzvn",
	"vdrz: gcvv * vgjt",
	"hpnl: dnws * jzql",
	"nfcr: 16",
	"zczj: 4",
	"rwhn: 3",
	"mmbj: 1",
	"fcbz: 16",
	"gljq: fqdl * jnmq",
	"dhzm: hhcg + pvrj",
	"gsmr: rcgq + lptm",
	"lwjj: 16",
	"npbl: 2",
	"bhsw: tjqb + cshm",
	"nvjg: svfj + dvnp",
	"mpqg: vzdv / rspq",
	"rjlw: mbmp - brfq",
	"vtbd: pvqb / dfbw",
	"wwls: 6",
	"ljhv: fcjm * vgpd",
	"wjhw: vqdv * nncw",
	"qtsc: gppp / cmtc",
	"dbmc: mssc + ffdv",
	"npgp: whgg + cgfd",
	"clhm: 5",
	"lnlm: svdm * bgzp",
	"mdgm: 14",
	"wfnf: 2",
	"hdbc: jqzf * mptg",
	"jrss: 5",
	"vrjg: qnhh * ndpl",
	"bvnv: jcrj * wdlv",
	"zqzl: fmrp * qsvc",
	"nsqr: lqml * nftz",
	"shzt: tbtc + wslg",
	"jgmc: qlvv * jphb",
	"mmpf: 2",
	"njfs: wmlm - jfvf",
	"hvcj: 3",
	"wgcp: dsng * lnbs",
	"mzzg: svlb + fggl",
	"cwhq: rmln * wvmd",
	"wqht: fjzn * jpdf",
	"trqs: 2",
	"blvw: cmqt * ptwc",
	"zbvr: 2",
	"rnqw: gpwh * hchr",
	"ttrv: fswz * vndv",
	"lbhm: fnnl + qjgd",
	"phmr: 3",
	"vcqr: 20",
	"rgjj: 5",
	"nqvm: hfsw + cndd",
	"jqsw: 5",
	"jzqf: mnjc + pbqm",
	"jdbt: 2",
	"fpch: 10",
	"cfhc: 13",
	"fjzn: vdqv + wzth",
	"dpbz: 2",
	"wcng: hsbl + qsbw",
	"fvth: 2",
	"mhnd: fgqr * hmtz",
	"tnsh: 3",
	"tljm: 1",
	"tjfv: thmv * prnh",
	"lhfp: zssp + wtmq",
	"mplb: npfj - mrbb",
	"bwmz: nsqr + qgbp",
	"rnbp: 3",
	"bclh: 2",
	"pchs: pflc * mgmc",
	"ggmd: gcjv + llbz",
	"qjdm: 2",
	"vlrc: 1",
	"dpzf: 3",
	"nrlh: ghtl - mhqd",
	"gzcw: 2",
	"rgfm: rgnq * dfgz",
	"cqsq: pzzl / vlbt",
	"vpgm: hsgc * chfq",
	"nrtq: wvjq / gdzl",
	"cjmp: 3",
	"gtmt: gctz * mlpn",
	"lfzq: djnl * hcqh",
	"rwwr: 2",
	"qtrv: 3",
	"dfbw: 2",
	"wmzl: 13",
	"twlz: vgnz * qwwl",
	"nlvv: 2",
	"bnwm: 2",
	"nbsg: lvmv * ccrf",
	"rgdb: svsd * cnst",
	"nrpg: bblj + lzvm",
	"pvsn: jwht - wfjt",
	"jrpr: gdmv * ztgc",
	"smsl: hmpb + gtmc",
	"pvrg: rsrl * dclb",
	"qngb: tmnw * fwwg",
	"mjfm: 5",
	"swqf: 5",
	"gvnl: 2",
	"hlvb: pmpl + rhhw",
	"npwd: nswl / jjtj",
	"vdzb: jbvb * bwjn",
	"sqfh: zwld * jgmc",
	"jfgh: jvtp * qctv",
	"fggj: 1",
	"pnzf: 3",
	"lnwv: sntw + qhwn",
	"rvjp: 2",
	"fngj: 13",
	"wqfw: 9",
	"fcjm: 2",
	"vmjb: 5",
	"wqjh: ldfg + pdwn",
	"tdfl: hqsd * vwgp",
	"tgpp: 6",
	"thqq: mqtj / bmcl",
	"rsdq: przw * qrmb",
	"rldb: 5",
	"lbpn: 16",
	"jmhz: bqtg * bsdh",
	"lcdr: fgzh + qnwv",
	"qsfw: lfcf + jqdd",
	"hsft: 16",
	"hdrz: 3",
	"gfzz: vgll - wjhw",
	"jnjt: 2",
	"pqtl: 2",
	"jgnh: 5",
	"trqz: jbcl * hrnl",
	"qmdn: cjrn * lpgl",
	"rbzn: fscf + ntvs",
	"rlqd: 3",
	"gfhs: 11",
	"bscn: jzzd - tlvf",
	"ztgl: 4",
	"rmmp: jmcl + pmbz",
	"zzfb: 5",
	"gdwq: 9",
	"zcql: nmnd + rfwr",
	"mztf: 14",
	"hfjr: hjhh * vwhs",
	"zcpb: 1",
	"zvtl: 3",
	"fvzc: 8",
	"jtvv: 4",
	"qjqc: twql * cphh",
	"cvrf: ldwz / hrtc",
	"plsn: 18",
	"nfmn: 1",
	"fdgj: dvfl + lrbw",
	"lmjp: 15",
	"wtsb: bvnr + ntww",
	"hpqj: rjtf * zgfr",
	"qhpj: 2",
	"pbwv: ssmt + lwwn",
	"jmvh: 4",
	"gzlb: tqjz * gjww",
	"crll: fblz / dqhr",
	"vpfs: mfdh * mmqq",
	"wtvh: 12",
	"qnmw: 2",
	"vsjt: jhpv + pftm",
	"nmnd: vqpv - rzlz",
	"wbrf: 3",
	"vhsp: 14",
	"qwgp: 2",
	"nhns: 3",
	"mhgr: 4",
	"swtg: fbvf * hpqj",
	"sdjq: dpgq + gvbq",
	"hmcr: 13",
	"qqlp: mnrl * ttrf",
	"vqsm: ngph * zlpf",
	"pwvn: qjqc / bsch",
	"dbzq: 4",
	"zbdp: dnzw * ptmn",
	"jgrl: gnwv * tlrz",
	"wttr: flzc + dhzm",
	"qwdt: wwgq * mmpj",
	"pqnr: 5",
	"gpph: rhhm / mzqp",
	"slst: npcv * rdtm",
	"pdvd: 2",
	"lwrz: pfwt * ldrw",
	"vvfp: ldnb + ddrm",
	"gnvb: gbjq - sldd",
	"fgfd: rgmg - mhgr",
	"ttbz: 6",
	"pmpl: 4",
	"scps: 3",
	"mmtb: 2",
	"zdlb: 5",
	"tqfv: zbcd - vgvt",
	"gtvm: ctmz + pchs",
	"drvt: 2",
	"hfsw: cmps * pvrv",
	"bhrz: vlrq * bnwm",
	"mqst: 10",
	"lzfv: 4",
	"wccm: 6",
	"nhmp: qzrz * gshr",
	"gdrh: rfgq + nghl",
	"rnzz: wtsb * qjdm",
	"lsjt: tvjw + jvpq",
	"jmgl: 12",
	"cmps: 2",
	"vvcp: tzgc + jfgh",
	"vdhj: svcr * bsds",
	"llsm: jgnn + bwjh",
	"vwhv: 2",
	"rpvf: 5",
	"mhhq: 2",
	"wdgh: mtcc * cnss",
	"pwcd: fbvp * dccf",
	"dlzh: ccdm * gfjr",
	"btrg: 4",
	"pgmt: pdzp * gzgd",
	"nrrt: 6",
	"bfcn: pwzt * mqwb",
	"cjct: jvsc * cgmc",
	"fdsq: 3",
	"hsgj: 2",
	"ncqj: wlsp + pbnr",
	"qnms: 3",
	"wnhj: 2",
	"mqrz: mwcz * blmn",
	"mtff: 2",
	"vnzt: 2",
	"tdrs: gzhc + vtnp",
	"qgcr: 2",
	"phsc: lszd - wrzd",
	"wzwl: 2",
	"jlfv: jhbw * tsfr",
	"qmgt: 2",
	"sjwp: nhsh + zzcb",
	"lbhz: 2",
	"ggwq: 5",
	"lsgz: 2",
	"svtb: 3",
	"crqv: dhhr + lgrf",
	"jmmq: 2",
	"wghm: 2",
	"ttrf: 4",
	"dffc: 5",
	"mpbq: 10",
	"tjwg: ccrq / bqsb",
	"bzzz: mzqb * npbl",
	"ggwf: hcnj + ndbs",
	"bfvn: wrmc * ptwl",
	"bwjh: qlzq * zpnn",
	"mttw: jqcq * vjzc",
	"rlcw: 5",
	"tnrq: 10",
	"mtlm: 3",
	"hdbm: hmzn + qngv",
	"pjqw: ddfd * rmnq",
	"vnjw: fchj * ggws",
	"lzrm: 3",
	"rrtr: 2",
	"fmml: dnhj / jqwv",
	"tfdf: 17",
	"zjvd: bbbf - tgpp",
	"cjvl: ghpp * qhqz",
	"zhhg: pvfn * shzt",
	"hhpt: szjw * sngt",
	"dwwp: 2",
	"rsrt: 5",
	"fqvr: 3",
	"nwsp: 5",
	"ccbd: 4",
	"pgwz: 2",
	"zgzm: wmgw + ffbp",
	"dfbr: bbvr + pchj",
	"lrsm: 2",
	"vlhj: 12",
	"ggsl: ldhv - gntj",
	"mmsw: 8",
	"rsrl: 2",
	"fsnh: 6",
	"zbwp: 5",
	"zthj: 5",
	"mwlf: 8",
	"ttgw: 3",
	"gggv: 4",
	"ctnm: qhrc * wlzs",
	"dnzw: fsqj + vsjt",
	"ftml: jmmq * tbcf",
	"grcb: 6",
	"cvnd: 5",
	"hqsj: 1",
	"ndcb: 2",
	"smpt: 16",
	"fbhd: dwmt * jgvs",
	"frzv: 3",
	"bcrl: swmb * tghv",
	"rpjr: 6",
	"fcvf: 5",
	"crwr: nprf / bwhg",
	"ptch: gmww * sqbw",
	"hmzf: wjcp * bvtc",
	"fscf: rlnv + fplv",
	"lhtz: lwcw - dhcf",
	"tdqt: 5",
	"lfgg: 14",
	"zwld: bzfw * psmh",
	"wqqz: cdfm * znbs",
	"pzdh: 5",
	"svzc: 2",
	"wzth: jfps * dbzq",
	"qpzr: fcbn * gdwq",
	"fvff: jsql + qlnm",
	"pzlc: 1",
	"qlqm: wwls * gqbm",
	"nmlq: 3",
	"rssz: 3",
	"cggm: 1",
	"sbqw: 2",
	"gpcv: 2",
	"gnhq: 20",
	"hjll: 3",
	"vcld: mtlm + qscg",
	"blgh: bqth * rddc",
	"pdlv: 2",
	"jzzv: ddsb * dhgm",
	"gtlr: 5",
	"bpwp: 14",
	"ltjf: plvm * zpct",
	"wrvz: 2",
	"nfsr: 11",
	"qfnd: 4",
	"ntww: 4",
	"nrth: 3",
	"zglm: bdlh + jmvh",
	"sjjp: plzn * vdvv",
	"mjtz: cncp + wwjp",
	"fnfn: 2",
	"hphr: rjcz * nrtn",
	"rhmc: rthb * fnbw",
	"rzsj: pstq - rpsg",
	"rnth: 4",
	"lspz: 8",
	"rcgq: 10",
	"dwcw: wnnc + nmpq",
	"nqtb: bgnm * vhsp",
	"hmzp: 2",
	"gcjv: 7",
	"hhdz: vvcp * qrgd",
	"rjzs: pqhm * qghh",
	"jsbw: 14",
	"mpwj: 3",
	"qcsv: jcfw - lvbg",
	"dvnp: 5",
	"bbqg: 2",
	"sdnz: zftr + gpph",
	"jgvq: brns + mwlf",
	"twtc: 5",
	"zqvb: 4",
	"wjcp: 4",
	"qwwl: 3",
	"pqzs: 2",
	"bzcw: srtp / mtvl",
	"fjjn: 7",
	"hptc: 4",
	"gwcv: rdhz + shvg",
	"ldnb: vwjq * cblt",
	"blzm: 4",
	"wpzq: gwqf - vpsv",
	"bzmw: zwzq + fgpj",
	"nbcc: 4",
	"qjqz: 5",
	"pzrm: gztg * wfzp",
	"fwtf: swtg + dspt",
	"pftm: cvbq * lbtb",
	"rnhf: 1",
	"srtp: ffhp + ftjq",
	"wrdv: wmpl + psrl",
	"cfdv: wmnh + gtls",
	"ltzz: 6",
	"fbcg: 11",
	"mbms: 2",
	"srzd: pdvc * mhnd",
	"sjvs: 3",
	"tvsl: 6",
	"mqdh: 9",
	"rlwg: 10",
	"hvzr: 9",
	"mzqw: 3",
	"vrjc: 4",
	"njgs: wvzs + pszn",
	"mcsq: 3",
	"nvrc: vqsm + nvpg",
	"rhhw: bmwh * vmgl",
	"gjrs: ssqj + tfdf",
	"zbhm: wlpf + cjct",
	"rspq: 5",
	"fsnf: 2",
	"zlcf: wtvf * jqvm",
	"dnhj: lwwv * ggsl",
	"dscr: crfw - fdwc",
	"lzrs: scps * mvvb",
	"ttfl: vdjf / hqcc",
	"gwqj: 3",
	"qfgl: 2",
	"mrrf: bwmp + wzzt",
	"slhn: gqfw * gtld",
	"lhwh: 4",
	"gcqz: pqzs * qdsj",
	"jlrq: 8",
	"nglh: 4",
	"qppm: lnlm + zbhm",
	"dfgn: tqsj * vnzt",
	"qrfc: rpqg / ccrc",
	"dbcz: lfsd + fvff",
	"nmtf: ssvh + cflr",
	"jlgw: tdrs + gthl",
	"hbfw: wtvh + vlrc",
	"tprz: 4",
	"fgpg: zgwc * mpfp",
	"vsjs: hpls * qvtl",
	"jqwv: 2",
	"mpfp: svqw + mzqw",
	"scnm: 13",
	"szvv: 4",
	"cndd: nwwt * phpd",
	"ngfn: pfgp + tcvf",
	"sttz: rpnt + prcr",
	"csvh: 12",
	"zpsf: 16",
	"sfdm: mghd + stnq",
	"nvnv: 3",
	"nhrq: 3",
	"hgnd: 9",
	"bsds: 5",
	"gnwv: 3",
	"rqmm: 20",
	"wtmq: 9",
	"gczz: fgcf + nrtq",
	"qdbn: 5",
	"gfjr: lfgg * zqzg",
	"ttrr: 2",
	"zmgh: 2",
	"sdvt: cjjr + cdwp",
	"lgrf: hhbp * rwww",
	"gfpj: 6",
	"fmqq: 4",
	"zpwg: btng * ppdn",
	"vdvq: brbc + crds",
	"rndv: 4",
	"gvwd: vdjv + rdhb",
	"fcsl: 1",
	"rdtl: 3",
	"fqqm: dtvz * zbsh",
	"jtbm: 3",
	"lfpm: lnwj * ngmj",
	"bjhn: fjhd * vgzc",
	"nrqd: bbqg * vvfp",
	"mhtd: hqrp * pmlg",
	"sqvs: mtmh * wgjm",
	"vtnp: zlgj * ffbr",
	"ppdn: 5",
	"cgsb: 2",
	"gsjn: 5",
	"njwn: 7",
	"lvwf: 18",
	"chbb: 3",
	"czmr: nrqd * tzsj",
	"pcmh: 3",
	"sntw: zswr + mnmm",
	"jhlh: 13",
	"fwfn: gjmn * grcd",
	"pccm: 4",
	"hzld: grcb + gzvj",
	"pwnn: 4",
	"nhsp: 3",
	"whqv: 2",
	"vlrq: flhf + rtpp",
	"jqjr: cgps * qtwz",
	"qcnf: 1",
	"tqgf: msng - lldm",
	"jqlv: jbdw + wsfp",
	"brns: 3",
	"wzpw: 2",
	"cfnc: mrbg + trqz",
	"jmft: 7",
	"vjfs: bjvl * mggn",
	"dvcv: 3",
	"vlzb: vcrf * qfzb",
	"ghsc: tmzh * jzgz",
	"wvmd: fcbz + dcrj",
	"nfjc: 6",
	"gspn: cfhc + bzfn",
	"rvdf: qsfw + zcpb",
	"hzdl: 2",
	"dltv: jmrl + lqqw",
	"mzbt: 5",
	"mvsc: 2",
	"tzdz: 10",
	"ztvv: 19",
	"zvmn: 2",
	"fblz: hpnl + qngb",
	"vhwb: 4",
	"sswq: 16",
	"lhqc: mrzl * bhzq",
	"dzpg: crll * gbqd",
	"gdqc: tzsh + phsc",
	"zhfz: shbg / tjwn",
	"mjpj: 2",
	"hjbb: mrlm * qmgt",
	"fhhg: 9",
	"gntj: 10",
	"fflf: 1",
	"nppm: 2",
	"jspg: tnnr / zzhw",
	"lscn: 2",
	"shhw: 10",
	"jmvv: hvdb + ctlr",
	"bbvr: 9",
	"bgjs: 4",
	"lzvq: rjmp + tvws",
	"rjcz: 2",
	"fgrl: 2",
	"mnjc: jcnw + ddbt",
	"bgnm: 2",
	"cqhl: 10",
	"bqtg: 3",
	"gqjd: 5",
	"rdvt: 4",
	"qrfb: 20",
	"srpj: bhrz / tqph",
	"pldl: 3",
	"gbmh: 6",
	"pdmn: 2",
	"vlqj: 4",
	"jvdq: fsvl * gcqb",
	"mrbg: 5",
	"znbs: csvh - gcdm",
	"zzms: 11",
	"wgrl: bpqq + zphb",
	"mdff: 2",
	"tcbb: 13",
	"rwbc: 4",
	"jdvr: psch / wqdp",
	"rmnj: qcbl + pzmt",
	"mngc: 3",
	"wnlc: sdnz * fctr",
	"zpjw: 2",
	"wnnc: 16",
	"sstc: hzwq / fvth",
	"qqjv: sjmt + ptbt",
	"gpnm: 1",
	"mncp: nncl - szzh",
	"tqlw: nbsg + cjnl",
	"vfhv: rqwg + snvs",
	"vswd: 4",
	"zbcd: gspn + cpmm",
	"jcwd: nfgh * gpfw",
	"gthl: bsbt + tjqf",
	"hnmg: 5",
	"jgvs: cfdj / lmdr",
	"mbjr: 14",
	"cdfm: dntp * lmzz",
	"cncp: 5",
	"jmsf: 12",
	"vsgc: 7",
	"hrtc: 2",
	"nghl: 5",
	"rsdd: 15",
	"rswb: 11",
	"wmpl: mhbg + hvzr",
	"gwmj: 13",
	"cbdg: 5",
	"wmnh: 6",
	"hndh: 3",
	"zqtp: 2",
	"tbtc: 7",
	"dvvz: ttfl * rdqg",
	"hcnm: 5",
	"djtb: 2",
	"ztpj: 5",
	"mqbw: 3",
	"bblj: dfgn + qfcc",
	"qvtl: jcsn + fbhv",
	"crds: ttgw * smsl",
	"cjrn: nfvs * ssts",
	"hfwv: csht + jfqr",
	"qccz: 12",
	"svdc: 13",
	"bcwc: 4",
	"vgwv: 2",
	"nvjr: 3",
	"bpfm: wpzq * snsf",
	"mrnn: mshj * bmjs",
	"nclj: rwhn * bclh",
	"lmdr: 2",
	"szrw: 4",
	"gdmv: 2",
	"qldd: vhvq + qrdz",
	"pngd: zgzh + pbsg",
	"ffjp: bgjs * prdg",
	"ljff: wjnz + npgq",
	"jpqn: tljm + gwjn",
	"zhgp: cfls * jqlv",
	"ggnb: gczz + fqbc",
	"msng: 15",
	"ffdv: bncm / ptjr",
	"wmgg: 9",
	"pfgz: nztf * hdqv",
}

func TestDay21Part1(t *testing.T) {
	expectedRes := 32
	if res := day21Part1(input21); res != expectedRes {
		t.Errorf("expected res is %v,what we get is %v", expectedRes, res)
	}
}
